version: '3.8'

services:
  redis:
    image: redis:7.0.11
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped
  info-api:
    image: jcsouzafirst/info.api:latest
    container_name: info-api
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis-server
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: unless-stopped
  poke-api:
    image: jcsouzafirst/poke.api:latest
    container_name: poke-api
    depends_on:
      - redis
    environment:
      DEFAULT_ZONE: http://servico-descoberta:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    restart: unless-stopped
  pokemon-spa:
    image: jcsouzafirst/poke.front:latest
    container_name: poke-front
    depends_on:
      - redis
      - info-api
      - poke-api
    environment:
      - POKEAPI_URL=http://info-api/api/v2/pokemon/
      - API_BASE_URL=http://127.0.0.1:5000/api/v1
    ports:
      - "9090:80"
volumes:
  redis-data:
    driver: local

networks:
  mynetwork:
    driver: bridge